project:
  type: website

website:
  title: "Andrea Di Francia"
  site-url: https://andreadifra.github.io/Mywebsite/
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Projects
        href: projects.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com
  page-footer:
    left: |
      Website made with [Quarto](https://quarto.org), by Andrea DI Francia. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/).
    right:
      - icon: github
        href: https://github.com/andreadifra
      - icon: envelope
        href: mailto:andrea.l.difrancia@gmail.com
      - icon: linkedin
        href: https://linkedin.com/in/andreadifrancia

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    mainfont: "Atkinson Hyperlegible, sans-serif"
    monofont: "Fira Code, monospace"



